import type { ControlCenterSnapshot } from "./types";

const now = new Date();

function minutesAgo(minutes: number): string {
  return new Date(now.getTime() - minutes * 60_000).toISOString();
}

export const initialMockSnapshot: ControlCenterSnapshot = {
  mode: "mock",
  connection: "online",
  lastSyncedAt: now.toISOString(),
  home: {
    state: "emergency",
    label: "紧急告警",
    summary: "客厅的检测到疑似跌倒姿态等待确认。",
    activeZone: "客厅 / LIVING ROOM",
    updatedAt: minutesAgo(2),
  },
  trae: {
    state: "analyzing",
    label: "分析中",
    project: "家庭关怀事件分析",
    task: "结合姿态、持续时间与声音线索生成处理建议",
    progress: 68,
    suggestion: "建议先通过家庭终端发起语音确认；若 60 秒内无回应，再升级远程通知。",
    updatedAt: minutesAgo(1),
  },
  robot: {
    state: "standby",
    label: "待命",
    connection: "online",
    battery: 82,
    task: "等待经过确认的行动指令",
    updatedAt: minutesAgo(1),
  },
  devices: [
    {
      deviceId: "pc-core-01",
      name: "TRAEVIS PC Core",
      kind: "pc",
      zone: "书房",
      connection: "online",
      detail: "状态服务与 TRAE Adapter 运行中",
      lastSeen: minutesAgo(0),
      metricLabel: "CORE TEMP",
      metricValue: "46°C",
      adapterMode: "mock",
    },
    {
      deviceId: "home-node-rpi4-01",
      name: "家庭感知节点 01",
      kind: "home-node",
      zone: "客厅",
      connection: "online",
      detail: "运动检测运行中，YOLO 模型待实机部署",
      lastSeen: minutesAgo(0),
      metricLabel: "VISION FPS",
      metricValue: "4.8",
      adapterMode: "mock",
    },
    {
      deviceId: "camera-ov5647-01",
      name: "OV5647 Camera",
      kind: "camera",
      zone: "客厅",
      connection: "online",
      detail: "1920 × 1080 / 稀疏推理",
      lastSeen: minutesAgo(0),
      metricLabel: "FRAME AGE",
      metricValue: "0.2s",
      adapterMode: "mock",
    },
    {
      deviceId: "microphone-usb-01",
      name: "USB Microphone",
      kind: "microphone",
      zone: "客厅",
      connection: "degraded",
      detail: "设备已选择，真实采样尚未验收",
      lastSeen: minutesAgo(4),
      metricLabel: "INPUT LEVEL",
      metricValue: "--",
      adapterMode: "mock",
    },
    {
      deviceId: "badge-esp32-01",
      name: "TRAEVIS 实体终端",
      kind: "badge",
      zone: "书房",
      connection: "online",
      detail: "状态显示与用户确认入口",
      lastSeen: minutesAgo(1),
      metricLabel: "BATTERY",
      metricValue: "91%",
      adapterMode: "mock",
    },
    {
      deviceId: "robot-spider-01",
      name: "蜘蛛机器人",
      kind: "robot",
      zone: "书房",
      connection: "online",
      detail: "USB 转发链路待协议接入",
      lastSeen: minutesAgo(1),
      metricLabel: "BATTERY",
      metricValue: "82%",
      adapterMode: "mock",
    },
  ],
  events: [
    {
      schemaVersion: "1.0",
      eventId: "evt_20260731_fall_001",
      deviceId: "home-node-rpi4-01",
      source: "vision",
      type: "fall_suspected",
      level: "critical",
      state: "detected",
      occurredAt: minutesAgo(2),
      updatedAt: minutesAgo(2),
      zone: "客厅",
      confidence: 0.82,
      title: "检测到疑似跌倒姿态",
      summary: "人物姿态在低位持续 8 秒，需要人工确认；当前不能判定为真实跌倒。",
      adapterMode: "mock",
      payload: { duration_ms: 8_210, person_count: 1, evidence: "mock://snapshot/fall-001" },
    },
    {
      schemaVersion: "1.0",
      eventId: "evt_20260731_audio_001",
      deviceId: "microphone-usb-01",
      source: "audio",
      type: "audio_device_degraded",
      level: "warning",
      state: "detected",
      occurredAt: minutesAgo(6),
      updatedAt: minutesAgo(6),
      zone: "客厅",
      title: "麦克风输入尚未完成实机验收",
      summary: "设备配置已保存，但当前没有可确认的输入电平数据。",
      adapterMode: "mock",
      payload: { selected_device: "microphone-usb-01" },
    },
    {
      schemaVersion: "1.0",
      eventId: "evt_20260731_motion_003",
      deviceId: "home-node-rpi4-01",
      source: "vision",
      type: "motion_detected",
      level: "info",
      state: "resolved",
      occurredAt: minutesAgo(18),
      updatedAt: minutesAgo(16),
      zone: "门厅",
      confidence: 0.74,
      title: "门厅检测到活动",
      summary: "运动区域持续 1.2 秒，未触发人物告警。",
      acknowledgedAt: minutesAgo(17),
      acknowledgedBy: "local-demo-user",
      resolvedAt: minutesAgo(16),
      resolvedBy: "local-demo-user",
      adapterMode: "mock",
      payload: { changed_ratio: 0.19 },
    },
    {
      schemaVersion: "1.0",
      eventId: "evt_20260731_trae_002",
      deviceId: "pc-core-01",
      source: "trae",
      type: "analysis_ready",
      level: "info",
      state: "resolved",
      occurredAt: minutesAgo(31),
      updatedAt: minutesAgo(28),
      zone: "系统",
      title: "TRAE 已生成设备异常建议",
      summary: "建议重新枚举麦克风并进行 1 秒输入采样。",
      acknowledgedAt: minutesAgo(29),
      acknowledgedBy: "local-demo-user",
      resolvedAt: minutesAgo(28),
      resolvedBy: "local-demo-user",
      adapterMode: "mock",
      payload: { project: "家庭关怀事件分析" },
    },
    {
      schemaVersion: "1.0",
      eventId: "evt_20260731_robot_001",
      deviceId: "robot-spider-01",
      source: "robot",
      type: "robot_standby",
      level: "info",
      state: "resolved",
      occurredAt: minutesAgo(44),
      updatedAt: minutesAgo(42),
      zone: "书房",
      title: "蜘蛛机器人进入待命",
      summary: "执行队列为空，运动输出已停止。",
      acknowledgedAt: minutesAgo(43),
      acknowledgedBy: "local-demo-user",
      resolvedAt: minutesAgo(42),
      resolvedBy: "local-demo-user",
      adapterMode: "mock",
      payload: { motion: "stop" },
    },
  ],
  commands: [
    {
      commandId: "cmd_20260731_003",
      requestId: "req_20260731_003",
      target: "trae",
      input: "分析疑似跌倒事件并给出确认建议",
      status: "running",
      requestedAt: minutesAgo(2),
      updatedAt: minutesAgo(1),
      adapterMode: "mock",
    },
    {
      commandId: "cmd_20260731_002",
      requestId: "req_20260731_002",
      target: "home-node",
      input: "刷新本地媒体设备状态",
      status: "succeeded",
      requestedAt: minutesAgo(12),
      updatedAt: minutesAgo(11),
      result: "设备清单已更新",
      adapterMode: "mock",
    },
    {
      commandId: "cmd_20260731_001",
      requestId: "req_20260731_001",
      target: "robot",
      input: "停止所有运动",
      status: "succeeded",
      requestedAt: minutesAgo(45),
      updatedAt: minutesAgo(44),
      result: "机器人已进入待命",
      adapterMode: "mock",
    },
  ],
  services: [
    { serviceId: "backend-core", name: "Control Center Backend", connection: "online", adapterMode: "mock", version: "0.1.0", latency: "in-process", detail: "浏览器 Mock 统一状态投影" },
    { serviceId: "devices-module", name: "Devices Module", connection: "degraded", adapterMode: "mock", version: "0.1.0", latency: "in-process", detail: "6 个设备，包含受限连接" },
    { serviceId: "events-module", name: "Events Module", connection: "online", adapterMode: "mock", version: "0.1.0", latency: "in-process", detail: "结构化事件流" },
    { serviceId: "trae-adapter", name: "TRAE Adapter", connection: "online", adapterMode: "mock", version: "0.1.0", latency: "in-process", detail: "模拟 TRAE 命令生命周期" },
    { serviceId: "robot-adapter", name: "Robot Adapter", connection: "online", adapterMode: "mock", version: "0.1.0", latency: "in-process", detail: "模拟机器人结构化动作" },
  ],
  resources: [
    { id: "cpu", label: "PC CORE LOAD", value: 42, displayValue: "42%", tone: "green", history: [28, 35, 31, 46, 38, 44, 42] },
    { id: "vision", label: "VISION PIPELINE", value: 61, displayValue: "4.8 FPS", tone: "cyan", history: [45, 52, 63, 58, 67, 59, 61] },
    { id: "memory", label: "MEMORY BUFFER", value: 34, displayValue: "2.7 / 8 GB", tone: "yellow", history: [21, 26, 28, 29, 31, 33, 34] },
    { id: "alerts", label: "ALERT PRESSURE", value: 76, displayValue: "1 CRITICAL", tone: "red", history: [8, 12, 16, 22, 38, 58, 76] },
  ],
};
